#!/usr/bin/env zsh
autoload -Uz array_contains

local array=()
local ref=$1

local value; for value in ${(P)ref}; do
    array_contains array "$value"
    [[ $? -ne 0 ]] && array+=("$value")
done

set -A "$ref" $array

return 0
