#!/usr/bin/env zsh

local default_fpaths=(
    "/usr/local/share/zeropoint/autoload/"*(N)
    "${ZDOTDIR:-$HOME}/.zautoload"
)

local p; for p in $default_fpaths; do
    if [[ ${fpath[(i)$p]} -gt ${#fpath} ]]; then
        fpath=("$p" $fpath)
    fi
done

mkdir -p "${ZDOTDIR:-$HOME}/.zautoload"

HISTFILE=${ZDOTDIR:-$HOME}/.zshhistory
HISTSIZE=5000
SAVEHIST=5000
CLICOLOR=1

export FPATH
export PATH
export HISTFILE
export HISTSIZE
export SAVEHIST
export CLICOLOR
